-- 코드를 입력하세요
SELECT USER_ID,NICKNAME, 
CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소',
CONCAT_WS('-',LEFT(TLNO,3), MID(TLNO,4,4), RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD
LEFT JOIN USED_GOODS_USER 
ON USED_GOODS_BOARD.WRITER_ID=USED_GOODS_USER.USER_ID
GROUP BY USER_ID
HAVING COUNT(USER_ID) >= 3
ORDER BY USER_ID DESC