-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE STATUS WHEN 'DONE' THEN '거래완료' WHEN 'SALE' THEN '판매중' WHEN 'RESERVED' THEN '예약중'  END as STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = DATE(20221005)
ORDER BY BOARD_ID DESC